---
- name: clone pkgbuilds repository
  become: yes
  become_user: '{{ user_name }}'
  git:
    repo: 'https://github.com/bitkeen/pkgbuilds.git'
    dest: '{{ pkgbuilds_dir }}'
    version: master

- name: make and install dependency packages
  become: yes
  become_user: '{{ user_name }}'
  shell:
    cmd: yes | makepkg -si --cleanbuild --needed --rmdeps
    chdir: '{{ pkgbuilds_dir }}/{{ item }}'
  loop: '{{ dependencies }}'

- name: make and install packages
  become: yes
  become_user: '{{ user_name }}'
  command:
    cmd: makepkg -si --cleanbuild --noconfirm --needed --rmdeps
    chdir: '{{ pkgbuilds_dir }}/{{ item }}'
  loop: '{{ packages | difference(conflicts) | difference(dependencies) }}'

- name: make and install packages that cause conflicts
  become: yes
  become_user: '{{ user_name }}'
  shell:
    cmd: yes | makepkg -si --cleanbuild --needed --rmdeps
    chdir: '{{ pkgbuilds_dir }}/{{ item }}'
  loop: '{{ conflicts }}'

- name: clean up build products
  become: yes
  become_user: '{{ user_name }}'
  shell:
    cmd: git clean -dfx
    chdir: '{{ pkgbuilds_dir }}'
