---
- name: update ranger maps
  become: yes
  become_user: '{{ user_name }}'
  command:
    # Need to have $PATH set up, run a login shell.
    cmd: sh -cl 'get-ranger-maps'

- name: create the manual page index cache
  command:
    cmd: mandb -c

- name: run updatedb (mlocate)
  command:
    cmd: updatedb

- name: compile tmux-thumbs
  shell: 'cd {{ user_home }}/.tmux/plugins/tmux-thumbs && cargo build --release'

- name: configure qBittorrent
  become: yes
  become_user: '{{ user_name }}'
  community.general.ini_file:
    path: '{{ user_home }}/.config/qBittorrent/qBittorrent.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0644
  loop:
    - {
      section: 'LegalNotice',
      option: 'Accepted',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'Downloads\SavePath',
      value: '/home/user/downloads/torrents/'
    }
    - {
      section: 'Preferences',
      option: 'Advanced\TrayIconStyle',
      value: 'MonoDark'
    }
    - {
      section: 'Preferences',
      option: 'General\CloseToTray',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'General\CloseToTrayNotified',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'General\MinimizeToTray',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'General\MinimizeToTrayNotified',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'General\StartMinimized',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'General\SystrayEnabled',
      value: 'true'
    }
    - {
      section: 'Preferences',
      option: 'AddNewTorrentDialog\RememberLastSavePath',
      value: 'false'
    }

- name: configure keepassxc
  become: yes
  become_user: '{{ user_name }}'
  community.general.ini_file:
    path: '{{ user_home }}/.config/keepassxc/keepassxc.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0644
  loop:
    - {
      section: 'GUI',
      option: 'ApplicationTheme',
      value: 'dark'
    }

- name: configure Syncthing
  lineinfile:
    path: '{{ user_home }}/.config/syncthing/config.xml'
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
  loop:
    - {
      # Spaces are to keep the indentation level.
      line: '        <defaultFolderPath>~/sync</defaultFolderPath>',
      regexp: '<defaultFolderPath>.*</defaultFolderPath>'
    }
    - {
      # Web GUI.
      line: '        <address>127.0.0.1:8384</address>',
      regexp: '<address>127.0.0.1:8080</address>'
    }
  ignore_errors: yes

- name: disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

- name: add a shorter alias for localhost
  shell: 'grep "127\.0\.0\.1 lh" /etc/hosts || echo "127.0.0.1 lh" >> /etc/hosts'
