repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-json
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks:
    - id: isort
      args: ["--check"]

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.24.2
  hooks:
    - id: yamllint

- repo: https://github.com/Vimjas/vint
  rev: 471e70bfff02edab460bc238c2e6d8aa46197d60
  hooks:
    - id: vint
      # Pathogen and abp syntax are third-party.
      exclude: vim/.vim/autoload/pathogen.vim|vim/.vim/syntax/abp.vim
