services:
  - docker

script:
  - docker build -t bitkeen/dotfiles .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push bitkeen/dotfiles
    fi
