dist: bionic

git:
  submodules: false

services:
  - docker

before_install:
  - pip install yamllint==1.24.2

before_script:
  - yamllint .

script:
  - docker build -t "$DOCKER_USERNAME"/dotfiles .

after_success:
  - if [ "$TRAVIS_BRANCH" == "arch" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker push "$DOCKER_USERNAME"/dotfiles;
    fi
