extends: default

rules:
  braces: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  line-length: disable
  truthy: disable

ignore: |
  *
  !ansible/**
  !/.travis.yml
  !/.yamllint.yml
