---
- name: update the package database
  command:
    cmd: pacman -Sy

- name: install pacman packages
  pacman:
    name: '{{ item }}'
  loop: '{{ packages }}'

- name: install work-related pacman packages
  pacman:
    name: '{{ item }}'
  loop: '{{ work_packages }}'
