---
- name: update the package database
  command:
    cmd: pacman -Sy

- name: install dependencies
  pacman:
    name: '{{ item }}'
  loop: '{{ dependencies }}'

- name: install pacman packages
  pacman:
    name: '{{ item }}'
  loop: '{{ packages }}'

# Only run when WORK_MACHINE env var is set.
- name: install work-related pacman packages
  pacman:
    name: '{{ item }}'
  loop: '{{ work_packages }}'
  when: lookup("ansible.builtin.env", "WORK_MACHINE")
