---
- name: install pacman packages
  pacman:
    name:
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - android-tools # Required for scrcpy (from AUR)
      - anki
      - ansible-lint
      - arandr # Xrandr front-end
      - atool # A script for managing file archives of various types
      - asp # Arch Linux build source file management tool
      - base-devel
      - bat # Cat clone with syntax highlighting and git integration
      - bluez # Daemons for the bluetooth protocol stack
      - bluez-utils # Provides the bluetoothctl utility
      - blueman # Graphical bluetooth manager
      - picom # A compositor for X11, required for transparency
      - ctags # Universal ctags
      - dbeaver
      - docker
      - docker-compose
      - dunst # A customizable and lightweight notification-daemon
      - etckeeper # Store /etc in a VCS repository
      - exfat-utils
      - feh # Image viewer, currently only used to set backgrounds with .fehbg script
      - firefox
      - fzf
      - gnome-keyring # Stores passwords and encryption keys
      - gnome-themes-extra # Contains Adwaita theme
      - go-pie # Required for path-extractor (AUR), conflicts with go
      - gst-plugins-good # GStreamer open-source multimedia framework good plugins
      - gst-plugins-ugly # GStreamer open-source multimedia framework ugly plugins
      - gvim
      - gimp
      - guvcview # Webcam capturing interface
      - i3-wm
      - imagemagick # An image viewing/manipulation program
      - ipython
      - jq # Command-line JSON processor
      - keepassxc
      - libsecret # Needed for storing Git credentials
      - libxml2 # XML parsing library, version 2, contains xmllint but is usually installed as a dependency for other packages
      - light # A program to control backlight controllers
      - lxappearance # Feature-rich GTK+ theme switcher of the LXDE Desktop
      - maim # Utility to take a screenshot
      - man-pages # Linux man pages
      - mediainfo # Supplies technical and tag information about a video or audio file (CLI interface), currently used for audio file previews in ranger
      - mpc
      - mpd
      - mpv
      - ncdu # NCurses Disk Usage
      - ncmpcpp
      - neofetch
      - networkmanager
      - networkmanager-openvpn
      - network-manager-applet
      - newsboat
      - npm # A package manager for javascript
      - ntfs-3g
      - openbsd-netcat # TCP/IP swiss army knife
      - pacman-contrib # Contributed scripts and tools for pacman systems
      - pulsemixer # CLI and curses mixer for pulseaudio
      - python-pip
      - python-virtualenvwrapper
      - ranger
      - redshift # Set color temperature of display according to time of day
      - ripgrep
      - simplescreenrecorder
      - reflector # A script to retrieve and filter the latest Pacman mirror list
      - seahorse # GNOME application for managing PGP keys
      - shellcheck # Shell script analysis tool
      - solaar # Device manager for Logitech's Unifying receiver peripherals
      - stow
      - sxhkd
      - sxiv # Simple X Image Viewer
      - syncthing # Open Source Continuous Replication / Cluster Synchronization Thing
      - syncthing-gtk # GTK3 based GUI and notification area icon for Syncthing
      - tidy # A tool to tidy HTML code
      - thunar # File Manager for the Xfce Desktop Environment
      - thunderbird
      - thunderbird-extension-enigmail
      - tmux
      - tor
      - torsocks # Wrapper to safely torify applications
      - transmission-gtk
      - ttf-font-awesome # Iconic font
      - udiskie
      - udisks2
      - unclutter # A small program for hiding the mouse cursor
      - unzip # For extracting and viewing files in .zip archives
      - urxvt-perls
      - vint # Lint tool for Vim script Language
      - virtualbox
      - virtualbox-guest-iso # Guest Additions CD image
      - wireshark-cli # Network traffic and protocol analyzer/sniffer - CLI tools and data files
      - xclip
      - xcursor-vanilla-dmz # Vanilla DMZ cursor theme
      - xmlstarlet # Command line utilities for XML
      - xorg-server
      - xorg-xev # Print contents of X events
      - xorg-xprop # Property displayer for X
      - xsecurelock # X11 screen lock utility
      - yamllint # Linter for YAML files
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
      - zip # Compressor/archiver for creating and modifying zipfiles
