---
- name: install pacman packages
  pacman:
    name:
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - android-tools # Required for scrcpy (from AUR).
      - anki
      - arandr # Xrandr front-end
      - picom # A compositor for X11, required for transparency
      - ctags # Universal ctags
      - dbeaver
      - dmenu
      - docker
      - docker-compose
      - dunst # A customizable and lightweight notification-daemon
      - etckeeper # Store /etc in a VCS repository
      - exfat-utils
      - feh # Image viewer, currently only used to set backgrounds with .fehbg script
      - firefox
      - fzf
      - gnome-themes-extra # Contains Adwaita theme.
      - gvim
      - gimp
      - guvcview # Webcam capturing interface
      - i3-wm
      - i3blocks
      - imagemagick # An image viewing/manipulation program
      - ipython
      - jq # Command-line JSON processor
      - keepassxc
      - libxml2 # XML parsing library, version 2, contains xmllint but is usually installed as a dependency for other packages
      - light # A program to control backlight controllers
      - maim # Utility to take a screenshot
      - man-pages # Linux man pages
      - mediainfo # Supplies technical and tag information about a video or audio file (CLI interface), currently used for audio file previews in ranger
      - mpc
      - mpd
      - mpv
      - ncdu # NCurses Disk Usage
      - ncmpcpp
      - neofetch
      - network-manager-applet
      - ntfs-3g
      - pulsemixer # CLI and curses mixer for pulseaudio
      - python-virtualenvwrapper
      - redshift # Set color temperature of display according to time of day
      - ripgrep
      - rxvt-unicode
      - shellcheck # Shell script analysis tool
      - stow
      - sxiv # Simple X Image Viewer
      - syncthing # Open Source Continuous Replication / Cluster Synchronization Thing
      - syncthing-gtk # GTK3 based GUI and notification area icon for Syncthing
      - tidy # A tool to tidy HTML code
      - thunar # File Manager for the Xfce Desktop Environment
      - thunderbird
      - tmux
      - tor
      - torsocks # Wrapper to safely torify applications
      - transmission-gtk
      - unclutter # A small program for hiding the mouse cursor
      - urxvt-perls
      - virtualbox
      - virtualbox-guest-iso # Guest Additions CD image
      - xclip
      - xcursor-vanilla-dmz # Vanilla DMZ cursor theme
      - xmlstarlet # Command line utilities for XML
      - xorg-server
      - xsecurelock # X11 screen lock utility
      - zathura
      - zathura-djvu
      - zathura-pdf-mupdf
