---
- name: check if transmission config exists
  become: yes
  become_user: '{{ user_name }}'
  stat:
    path: '{{ settings_file }}'
  register: settings

- name: create transmisison config file, if it doesnt exist already
  become: yes
  become_user: '{{ user_name }}'
  when: not settings.stat.exists
  block:
    - name: create the parent directory
      file:
        path: '{{ config_dir }}'
        state: directory

    - name: create transmisison config file, if it doesnt exist already
      copy:
        src: settings.json
        dest: '{{ settings_file }}'
        mode: 0600

- name: update settings.json if the file already exists
  become: yes
  become_user: '{{ user_name }}'
  when: settings.stat.exists
  block:
    - name: register lines with keys from settings.json
      become: yes
      become_user: '{{ user_name }}'
      command:
        cmd: grep -P '^\s*".*":' {{ role_path }}/files/settings.json
      register: lines

    - name: register keys from settings.json
      become: yes
      become_user: '{{ user_name }}'
      command:
        cmd: 'jq -r keys[] {{ role_path }}/files/settings.json'
      register: keys

    - name: paste lines into transmisison config file, if it already exists
      lineinfile:
        path: '{{ settings_file }}'
        line: '{{ item.0 }}'
        regexp: '^\s*"{{ item.1 }}":'
      loop: '{{ lines.stdout_lines|zip(keys.stdout_lines)|list }}'
