---
# Some packages have multiple dependencies to choose from.
dependencies:
  - wireplumber

packages:
  - adobe-source-han-sans-otc-fonts
  - adobe-source-han-serif-otc-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - android-tools  # Required for scrcpy (from AUR)
  - ansible-lint
  - arandr  # Xrandr front-end
  - aria2  # Download utility, used as external downloader to speed up youtube-dl.
  - asp  # Arch Linux build source file management tool
  - autopep8  # A tool that automatically formats Python code to conform to the PEP 8 style guide
  - base-devel
  - bash-language-server  # Bash LSP
  - bat  # Cat clone with syntax highlighting and git integration
  - bind  # DNS server. Provides dig, host, nslookup and other tools.
  - blueman  # Graphical bluetooth manager
  - bluez  # Daemons for the bluetooth protocol stack
  - bluez-utils  # Provides the bluetoothctl utility
  - ccls  # C/C++/ObjC language server
  - ctags  # Universal ctags
  - dnsmasq
  - docker
  - docker-compose
  - dunst  # A customizable and lightweight notification-daemon
  - etckeeper  # Store /etc in a VCS repository
  - exfat-utils
  - expac  # pacman database extraction utility
  - fdupes  # Identify or delete duplicate files residing within specified directories
  - ffmpegthumbnailer  # Video thumbnainer for previews in ranger
  - firefox
  - flake8  # The modular source code checker: pep8, pyflakes and co
  - fwupd  # Simple daemon to allow session software to update firmware
  - fzf
  - gimp
  - git
  - gnome-keyring  # Stores passwords and encryption keys
  - gnome-themes-extra  # Contains Adwaita theme
  - go-pie  # Required for path-extractor (AUR), conflicts with go
  - gst-plugins-good  # GStreamer open-source multimedia framework good plugins
  - gst-plugins-ugly  # GStreamer open-source multimedia framework ugly plugins
  - gucharmap  # Gnome Unicode character map
  - gvim  # Vim in GVim package has support for system clipboard
  - hey  # HTTP load generator
  - hsetroot  # Tool to set wallpapers.
  - i3-wm
  - imagemagick  # An image viewing/manipulation program
  - intel-ucode  # Microcode update files for Intel CPUs
  - ipython
  - jq  # Command-line JSON processor
  - keepassxc
  - libsecret  # Needed for storing Git credentials
  - libxml2  # XML parsing library, version 2, contains xmllint but is usually installed as a dependency for other packages
  - light  # A program to control backlight controllers
  - lsof  # Lists open files for running Unix processes
  - lxappearance-gtk3  # Feature-rich GTK+ theme switcher of the LXDE Desktop
  - maim  # Utility to take a screenshot
  - man-db  # A utility for reading man pages
  - man-pages  # Linux man pages
  - mediainfo  # Supplies technical and tag information about a video or audio file (CLI interface), currently used for audio file previews in ranger
  - mlocate  # Merging locate/updatedb implementation
  - moreutils  # Provides ifne and sponge utilities among others.
  - mpc  # Command line interface to MPD
  - mpd  # Music Player Daemon
  - mpv  # Media player
  - ncdu  # NCurses Disk Usage
  - ncmpcpp  # MPD TUI client
  - neofetch  # System information tool
  - network-manager-applet
  - networkmanager
  - networkmanager-openvpn
  - newsboat
  - nfs-utils  # Support programs for Network File Systems.
  - npm  # A package manager for javascript
  - ntfs-3g
  - openbsd-netcat  # TCP/IP swiss army knife
  - pacman-contrib  # Contributed scripts and tools for pacman systems
  - pcsclite  # For CryptoPlugin
  - perf  # Linux kernel performance auditing tool.
  - picom  # A compositor for X11, required for transparency
  - pipewire
  - pipewire-pulse
  - pipewire-alsa  # For PipeWire to manage ALSA
  - powertop  # A tool to diagnose issues with power consumption and power management.
  - pulsemixer  # CLI and curses mixer for pulseaudio
  - python-cssbeautifier  # CSS unobfuscator and beautifier
  - python-jedi  # Awesome autocompletion for python, a dependency for ipython and python-language-server
  - python-lxml  # To run lxml-based code without a virtualenv.
  - python-pip
  - python-virtualenvwrapper
  - qbittorrent
  - ranger
  - redshift  # Set color temperature of display according to time of day
  - reflector  # A script to retrieve and filter the latest Pacman mirror list
  - ripgrep
  - rsync  # A fast and versatile file copying tool for remote and local files
  - ruby
  - rust
  - seahorse  # GNOME application for managing PGP keys
  - shellcheck  # Shell script analysis tool
  - simplescreenrecorder
  - sof-firmware  # Sound Open Firmware, needed for audio to work on X1 Carbon
  - solaar  # Device manager for Logitech's Unifying receiver peripherals
  - stow
  - strace  # A diagnostic, debugging and instructional userspace tracer
  - sxhkd
  - sxiv  # Simple X Image Viewer
  - syncthing  # Open Source Continuous Replication / Cluster Synchronization Thing
  - sysstat  # A collection of performance monitoring tools (iostat,isag,mpstat,pidstat,sadf,sar)
  - telegram-desktop
  - terminus-font  # Monospace bitmap font, used in vconsole
  - texlive-bin
  - texlive-latexextra
  - thunar  # File Manager for the Xfce Desktop Environment
  - thunderbird
  - tidy  # A tool to tidy HTML code
  - time  # Provides /usr/bin/time. By default, only shell's builtin is available.
  - tlp  # Linux Advanced Power Management.
  - tmux
  - tor
  - torsocks  # Wrapper to safely torify applications
  - traceroute  # Tracks the route taken by packets over an IP network
  - ttf-dejavu
  - ttf-font-awesome  # Iconic font
  - ttf-liberation  # Font family which aims at metric compatibility with Arial, Times New Roman, and Courier New
  - ttf-opensans  # Sans-serif typeface commissioned by Google, needed for telegram-desktop
  - udiskie
  - udisks2
  - ueberzug  # Used in ranger for image previews.
  - unclutter  # A small program for hiding the mouse cursor
  - units  # Convert between different units
  - unzip  # For extracting and viewing files in .zip archives
  - urxvt-perls
  - vint  # Lint tool for Vim script Language
  - virtualbox-host-modules-arch
  - virtualbox
  - virtualbox-guest-iso  # Guest Additions CD image
  - w3m  # Text-based Web browser as well as pager, used for html previews in ranger
  - whois  # Intelligent WHOIS client
  - wireshark-cli  # Network traffic and protocol analyzer/sniffer - CLI tools and data files
  - xclip  # Command line interface to the X11 clipboard
  - xcursor-vanilla-dmz  # Vanilla DMZ cursor theme
  - xdg-user-dirs  # Manage user directories like ~/Pictures and ~/Music
  - xmlstarlet  # Command line utilities for XML
  - xorg-server
  - xorg-xev  # Print contents of X events
  - xorg-xinit  # X Window System initializer
  - xorg-xinput  # Small commandline tool to configure devices
  - xorg-xprop  # Property displayer for X
  - xsecurelock  # X11 screen lock utility
  - yamllint  # Linter for YAML files
  - youtube-dl
  - zathura  # Document viewer
  - zathura-djvu
  - zathura-pdf-mupdf
  - zip  # Compressor/archiver for creating and modifying zipfiles
  - zsh

work_packages:
  - aws-cli  # Universal Command Line Interface for Amazon Web Services
  - chromium  # For Google Chat app.
  - kubectl  # A command line tool for communicating with a Kubernetes API server.
  - mariadb-clients  # For mysqldump
  - plantuml  # Component that allows to quickly write uml diagrams
  - redis
  - terraform
  - xournalpp  # For signing PDFs
