#!/bin/sh
# Startup script for both bash and zsh.
# External to ~/.config/shell in order to avoid recursion.

for f in ~/.config/shell/*; do source "$f"; done

_source_if_exists() {
    # Source a file if it exists.
    [ "$#" -ne 1 ] && return 1
    [ -f "$1" ] && source "$1" || return 1
}

[ -n "$ZSH_VERSION" ] && ext='zsh' || ext='bash'
fzf_bindings_file="/usr/share/fzf/key-bindings.$ext"
fzf_completion_file="/usr/share/fzf/completion.$ext"
base16_shell_dir="$HOME/.config/base16-shell/"
venv_wrapper_file="/usr/bin/virtualenvwrapper_lazy.sh"

_source_if_exists "$fzf_bindings_file"
_source_if_exists "$fzf_completion_file"
_source_if_exists "$venv_wrapper_file"

# Base16 Shell.
set_up_base_16() {
    [ -n "$PS1" ] && \
        [ -s "$base16_shell_dir/profile_helper.sh" ] && \
            eval "$("$base16_shell_dir/profile_helper.sh")"
}

if [ -n "$TMUX" ]; then
    # Don't set up base16-shell when in a dropdown terminal. 
    # This is to keep color overrides (for transparency) in .Xresources.
    tmux_s_name="$(tmux display-message -p '#S')"
    [ "$tmux_s_name" != 'dropdown' ] && [ "$tmux_s_name" != 'misc' ] && \
        set_up_base_16
else
    set_up_base_16
fi
