#!/bin/sh
# Startup script for both bash and zsh.
# External to ~/.config/shell in order to avoid recursion.

for f in ~/.config/shell/*; do . "$f"; done

_source_if_exists() {
    # Source a file if it exists.
    [ "$#" -ne 1 ] && return 1
    [ -f "$1" ] && . "$1" || return 1
}

[ -n "$ZSH_VERSION" ] && ext='zsh' || ext='bash'
fzf_bindings_file="/usr/share/fzf/key-bindings.$ext"
fzf_completion_file="/usr/share/fzf/completion.$ext"
base16_shell_dir="$HOME/.config/base16-shell"
venv_wrapper_file='/usr/bin/virtualenvwrapper_lazy.sh'
# Provides __git_ps1() to show current Git branch in shell prompt.
git_prompt_file='/usr/share/git/completion/git-prompt.sh'

_source_if_exists "$fzf_bindings_file"
_source_if_exists "$fzf_completion_file"
_source_if_exists "$venv_wrapper_file"

if _source_if_exists "$git_prompt_file"; then
    # Add a '$' in the __git_ps1 output to show stashed changes
    # are present.
    export GIT_PS1_SHOWSTASHSTATE=1
    # Show unstaged (*) and staged (+) changes next to the branch name.
    export GIT_PS1_SHOWDIRTYSTATE=1
    # If there are untracked files, then a '%' will be shown.
    export GIT_PS1_SHOWUNTRACKEDFILES=1
    # Indicate difference between HEAD and its upstream.
    export GIT_PS1_SHOWUPSTREAM="auto"
fi

# Base16 Shell.
set_up_base_16() {
    [ -n "$PS1" ] && \
        [ -s "$base16_shell_dir/profile_helper.sh" ] && \
            source "$base16_shell_dir/profile_helper.sh"
    source "$base16_shell_dir/scripts/base16-tomorrow-night.sh"
}

if [ -n "$TMUX" ]; then
    # Don't set up base16-shell when in a dropdown terminal.
    # This is to keep color overrides (for transparency) in .Xresources.
    tmux_s_name="$(tmux display-message -p '#S')"
    set_up_base_16
else
    set_up_base_16
fi
