#!/bin/sh
# Startup script for both bash and zsh.
# External to ~/.config/shell in order to avoid recursion.

for f in ~/.config/shell/*; do source "$f"; done

_source_if_exists() {
    # Source a file if it exists.
    [ "$#" -ne 1 ] && return 1
    [ -f "$1" ] && source "$1" || return 1
}

venv_wrapper_file="/usr/bin/virtualenvwrapper_lazy.sh"

# Exported in .bashrc and .zshrc.
_source_if_exists "$FZF_BINDINGS_FILE"
_source_if_exists "$FZF_COMPLETION_FILE"
_source_if_exists "$venv_wrapper_file"
