#!/bin/sh
# Aliases for Git.

git_alias() {
    case "$1" in
        rt|root)
            # Change working directory to the git root if the current
            # working directory is inside of a git repository.
            # First check that we're in a Git repo.
            'git' rev-parse --git-dir > /dev/null &&
                cd "$(git rev-parse --show-toplevel)" ||
                return 1;;
        shr)
            # Run git stash and repeat the previous command.
            [ -n "$ZSH_VERSION" ] && hist_command='r' || hist_command='fc -s'
            'git' stash &&
                $hist_command ||
                return 1;;
        shrp)
            # Run git stash, repeat the previous command and pop from
            # the stash.
            [ -n "$ZSH_VERSION" ] && hist_command='r' || hist_command='fc -s'
            'git' stash &&
                $hist_command &&
                'git' stash pop ||
                return 1;;
        shup)
            # Stash, rebase, push, pop.
            'git' stash &&
                'git' pull --rebase &&
                'git' push &&
                'git' stash pop ||
                return 1;;
        *)
            'git' "$@" ||
                return 1;;
    esac
}
