#!/bin/sh
ps1_venv() {
    # Strip out the path and just leave the env name.
    [ -n "$VIRTUAL_ENV" ] && echo " (${VIRTUAL_ENV##*/})"
}


ps1_vim() {
    [ -n "$VIMRUNTIME" ] && echo ' (in vim)'
}


ps1_ranger() {
    [ -n "$RANGER_LEVEL" ] && echo ' (in ranger)'
}


ps1_git() {
    # Redirect stderr for cases when __git_ps1 wasn't sourced.
    __git_ps1 2>/dev/null
}


ps1_status() {
    last_status="$?"
    [ "$last_status" = '0' ] && echo '+' || echo '-'
}


up() {
    # Go up $1 directories.
    # If $1 is omitted or is not an integer, go up 1 directory.
    dir=''
    if echo "$1" | grep -Eq '^[0-9]+$'; then
        for _ in $(seq "$1")
        do
            dir="$dir../"
        done
    else
        dir='..'
    fi
    cd "$dir"
}


uf() {
    # Go up the directory structure.
    # Select a parent dir through fzf.
    [ "$PWD" = '/' ] && echo "Can't go up from /" && return 1

    dirs=''
    append_dir() {
        [ -n "${dirs}" ] &&
            dirs="${dirs}\n${1}" ||
            dirs="${1}"
    }

    tmp_path="$PWD"
    while [ -n "${tmp_path}" ]; do
        tmp_path="$(echo "${tmp_path}" | sed 's;/[^/]*$;;')"
        [ -z "${tmp_path}" ] && break
        append_dir "${tmp_path}"
    done
    append_dir '/'

    dir="$(echo "$dirs" | fzf --reverse --height=40%)"
    [ -n "$dir" ] && cd "$dir" || return
}


ww() {
    # Open index file of the $1 wiki (the first one if $1 is omitted).
    vim -c "execute \"normal $1\<Plug>VimwikiIndex\""
}


fzg() {
    # Open a directory from special files containing a list of shortcuts.
    dir="$(fzf-shortcuts ~/.config/shortcuts ~/.config/shortcuts.local)"
    [ -n "$dir" ] && cd "$dir" || return 1
}


vim_session_venv() {
    # Get a directory to venv mapping from a file, activate venv
    # before launching vim with the session of the directory.
    # Do not change venv if already in a venv.
    #
    # File example:
    # /home/user/directory1 venv1
    # /home/user/directory2 venv2
    #
    # Usage example:
    # vim_session_venv ~/.config/venv_mapping
    if [ -z "$VIRTUAL_ENV" ]; then
        venv_mapping_file="$1"
        if [ -n "$venv_mapping_file" ] && [ -f "$venv_mapping_file" ]; then
            venv_name="$(grep "$(pwd)" "$venv_mapping_file" | awk '{ print $2 }')"
            [ -n "$venv_name" ] && workon "$venv_name"
        fi
    fi

    vim -c 'WrappedObsession'
}


ranger_cd() {
    # Automatically change the directory in bash after closing ranger.
    # Source:
    # https://github.com/ranger/ranger/blob/master/examples/bash_automatic_cd.sh
    # The same script can be found locally:
    # /usr/share/doc/ranger/examples/bash_automatic_cd.sh
    #
    # This is a function for automatically changing the directory to
    # the last visited one after ranger quits.
    # To undo the effect of this function, you can type "cd -" to return to the
    # original directory.
    temp_file="$(mktemp -t "ranger_cd.XXXXXXXXXX")"
    'ranger' --choosedir="$temp_file" -- "${@:-$PWD}"
    chosen_dir="$(cat -- "$temp_file")"
    if [ -f "$temp_file" ] && [ "$chosen_dir" != "$PWD" ]; then
        cd -- "$chosen_dir"
    fi
    rm -f -- "$temp_file"
}


wrap_ranger() {
    # Temporary workaround for tmux renaming problem.
    [ -z "$TMUX" ] || current_window_name="$(tmux display-message -p '#W')"
    tmux rename-window 'ranger'
    # The ranger_cd version switches the directory in bash on exit,
    # ranger-shell allows to expand shell aliases inside the :shell
    # command.
    SHELL=~/.local/bin/ranger-shell ranger_cd
    [ -z "$current_window_name" ] || tmux rename-window "$current_window_name"
}


fm() {
    # Go to a mounted partition's directory.
    choice="$(fzf-mounted)"
    [ -n "$choice" ] && ranger_cd "$choice"
}


gfm() {
    choice="$(fzf-mounted)"
    [ -n "$choice" ] && cd "$choice"
}


copyline() {
    # Copy current command, bash-specific.
    # From https://stackoverflow.com/a/23710535.
    # Should be bound to a shortcut in bash, depends on `xclip-in`
    # wrapper script.
    printf %s "$READLINE_LINE" | xclip-in
}


clc() {
    # Copy last command.
    if [ -n "$ZSH_VERSION" ]; then
        history |
            awk 'END{for (i=2; i<NF; i++) printf $i " "; print $NF}' |
            xclip-in -rmlastnl
    else
        history -p '!!' |
            awk 'END{print}' |
            xclip-in -rmlastnl
    fi
}


rpc() {
    rpw "$1" | xclip-in -f
}


wo() {
    # virtualenvwrapper's workon with fzf selection if no argument is supplied.
    [ -z "$1" ] && set -- "$(workon | fzf)"
    [ -z "$1" ] && return 1
    workon "$@"
}
