#!/bin/sh
# Reload .Xresources.
alias xup='xrdb ~/.Xresources'
# Reload .bashrc.
alias bup='[ -z "$ZSH_VERSION" ] && source ~/.bashrc || echo "Not in bash"'
# Reload .zshrc.
alias zup='[ -n "$ZSH_VERSION" ] && exec zsh || echo "Not in zsh"'
# Reload .tmux.conf.
alias tup='tmux source-file ~/.tmux.conf'
# Reload Readline's .inputrc.
alias rup='bind -f ~/.inputrc'
# Restart i3.
alias iup='i3-msg restart'

alias ls='ls -F --color=auto'
# -h - with -l and -s, print sizes like 1K 234M 2G etc.
alias ll='ls -AlFh'

# -r - copy directories recursively
# -i - prompt before overwrite
alias cp='cp -ir'

# -i - prompt before overwrite
alias mv='mv -i'

# -p - no error if existing, make parent directories as needed.
# -v - print a message for each created directory.
alias mkd='mkdir -pv'

alias tch='touch'

# Highlight matches, ignore case distinctions.
alias grep='grep --color=auto --ignore-case'
# -n - output line numbers
# -I - ignore binary files
alias gr='grep -n -I'

# -L - follow symbolic links
# Case-insensitive.
alias fn='find -L . -iname'
# Case-sensitive.
alias fnc='find -L . -name'

# Kill processes by name.
alias ka='killall'

# The space at the end allows the next command word following the alias
# to also be checked for alias expansion.
# -v flag makes sudo reset password timeout.
alias s='sudo -v; sudo '
alias sudo='sudo -v; sudo '

alias mk='make'

alias o='xdg-open'

alias p='pacman'

alias ranger='wrap_ranger'
alias f='wrap_ranger'

alias t='tmux'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'

alias v='vim'
alias vs='vim_session_venv ~/.config/venv_mapping'

alias nb='newsboat'

alias py='python'
alias ipy='ipython'
# Python virtualenvwrapper.
alias wo='workon'
alias deac='deactivate'
alias mkvenv='mkvirtualenv'
alias rmvenv='rmvirtualenv'

alias bandcamp-dl='bandcamp-dl --base-dir="$(xdg-user-dir DOWNLOAD)"/bandcamp-dl'

alias yd='youtube-dl'
# Download playlists using a separate config.
# The config specifies different directory structure.
alias ydp='youtube-dl --config-location ~/.config/youtube-dl-playlist.conf'
# There are options to download subtitles in the main config file,
# the subtitles are not needed for audio-only downloads, and can't
# be merged into an audio file, so a separate config file for audio
# is needed, without the subtitle options.
alias yda='youtube-dl --config-location ~/.config/youtube-dl-audio.conf'

# --auto-vertical-output - automatically switch to vertical output
# mode if the result is wider than the terminal width.
alias mycli='mycli --auto-vertical-output'

alias g='git_alias'
alias lab='alias-wrapper-lab'
alias l='lab'

alias systemctl='alias-wrapper-systemctl'
alias journalctl='alias-wrapper-journalctl'
alias sctl='systemctl'
alias sc='systemctl'
alias jctl='journalctl'
alias jc='journalctl'

alias docker='alias-wrapper-docker'
alias docker-compose='alias-wrapper-docker-compose'
alias d='docker'
alias c='docker-compose'

# Tor start/stop.
alias toron='sudo systemctl start tor.service'
alias toroff='sudo systemctl stop tor.service'

# Empty trash.
alias et='gio trash --empty'

alias nb='newsboat'

alias fzd='fzf-dbs ~/.config/db_connections.local'
alias fzk='fzf-kill'

alias timer='TIMER_SOUND="$HOME/.local/share/timer/sound-2.wav" timer'

alias drdf='docker run -it --rm bitkeen/dotfiles'

# Convert input to decimal byte values.
# Ignore grep aliases.
alias ascii="od -An -t dC | 'grep' -Po '\d.*(?=10)'"

alias yp='pwd | xclip-in -rmlastnl'

alias bs='~/.dotfiles/ansible/bootstrap'

# Clipboard.
alias xi='xclip-in'
alias xo='xclip-out'
