---
- name: gather facts
  setup:
    filter: ansible_interfaces

- name: check if running in docker
  set_fact:
    in_docker: '{{ "docker0" not in ansible_facts.interfaces }}'

- name: install unit files
  copy:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
  loop:
    - lock@.service
    - newsboat-reload.service
    - newsboat-reload.timer
    - pacman-update-files-database.service
    - pacman-update-files-database.timer
    - fetch-dotfiles.service
    - fetch-dotfiles.timer
    - docker-limit.slice

- name: reload units
  systemd:
    daemon_reload: yes
  when: not in_docker

- name: enable and start services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - bluetooth.service
    - docker.service
    - newsboat-reload.timer
    - pacman-update-files-database.timer
    - paccache.timer  # Discard unused packages weekly.
    - systemd-timesyncd.service  # Sync time.
    - fetch-dotfiles.timer
    - tlp.service
  when: not in_docker

- name: start docker resource limit slice
  systemd:
    name: docker-limit.slice
    state: started
  when: not in_docker

- name: enable screen lock service
  systemd:
    name: 'lock@{{ user_name }}'
    enabled: yes
  when: not in_docker

- name: copy udev rules
  copy:
    src: udev/50-monitor-hotplug.rules
    dest: /etc/udev/rules.d/

- name: restart systemd-udevd
  systemd:
    name: systemd-udevd
    state: restarted
  when: not in_docker

- name: install user unit files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: '{{ item }}'
    dest: '{{ user_home }}/.config/systemd/user/{{ item }}'
  loop:
    - monitor-hotplug@.service
    - battery-notification.service
    - xidlehook.service

- name: reload user units
  become: yes
  become_user: '{{ user_name }}'
  systemd:
    daemon_reload: yes
    scope: user
  when: not in_docker

- name: enable and start user services
  become: yes
  become_user: '{{ user_name }}'
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
    scope: user
  loop:
    - mpd.service
    - syncthing.service
    - battery-notification.service
    - xidlehook.service
  when: not in_docker
