---
- name: install unit files
  copy:
    src: '{{ item.unit_name }}'
    dest: '/etc/systemd/system/{{ item.unit_name }}'
  loop:
    - { unit_name: lock@.service }
    - { unit_name: newsboat-reload.service }
    - { unit_name: newsboat-reload.timer }
    - { unit_name: pacman-update-files-database.service }
    - { unit_name: pacman-update-files-database.timer }

- name: reload units
  systemd:
    daemon_reload: yes

- name: enable and start services
  systemd:
    name: "{{ item.unit_name }}"
    enabled: yes
    state: started
  loop:
    - { unit_name: docker.service }
    - { unit_name: newsboat-reload.timer }
    - { unit_name: pacman-update-files-database.timer }
    - { unit_name: paccache.timer } # Discard unused packages weekly.
    - { unit_name: systemd-timesyncd.service } # Sync time.

- name: enable screen lock service
  systemd:
    name: lock@user
    enabled: yes
