---
- name: install unit files
  copy:
    src: '{{ item.unit_name }}'
    dest: '/etc/systemd/system/{{ item.unit_name }}'
  loop:
    - { unit_name: lock@.service }
    - { unit_name: newsboat-reload.service }
    - { unit_name: newsboat-reload.timer }
    - { unit_name: pacman-update-files-database.service }
    - { unit_name: pacman-update-files-database.timer }
    - { unit_name: fetch-dotfiles.service }
    - { unit_name: fetch-dotfiles.timer }
    - { unit_name: toggle-monitor.service }

- name: reload units
  systemd:
    daemon_reload: yes

- name: enable and start services
  systemd:
    name: '{{ item.unit_name }}'
    enabled: yes
    state: started
  loop:
    - { unit_name: docker.service }
    - { unit_name: newsboat-reload.timer }
    - { unit_name: pacman-update-files-database.timer }
    - { unit_name: paccache.timer } # Discard unused packages weekly.
    - { unit_name: systemd-timesyncd.service } # Sync time.
    - { unit_name: fetch-dotfiles.timer }

- name: enable and start user services
  become: yes
  become_user: '{{ user_name }}'
  systemd:
    name: '{{ item.unit_name }}'
    enabled: yes
    state: started
    scope: user
  loop:
    - { unit_name: mpd.service }

- name: enable screen lock service
  systemd:
    name: lock@user
    enabled: yes

- name: copy udev rules
  copy:
    src: udev/50-monitor-hotplug.rules
    dest: /etc/udev/rules.d/

- name: restart systemd-udevd
  systemd:
    name: systemd-udevd
    state: restarted
