---
- name: install screen lock service file
  copy:
    src: 'lock@.service'
    dest: '/etc/systemd/system/lock@.service'

- name: reload units
  systemd:
    daemon_reload: yes

- name: enable screen lock service
  systemd:
    name: lock@user
    enabled: yes

- name: enable and start paccache.timer to discard unused packages weekly
  systemd:
    name: paccache.timer
    enabled: yes
    state: started

- name: enable and start systemd-timesyncd to sync time
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
    state: started
