---
- name: gather facts
  setup:
    filter: ansible_interfaces

- name: check if running in docker
  set_fact:
    in_docker: '{{ "docker0" not in ansible_facts.interfaces }}'

- name: install unit files
  copy:
    src: '{{ item }}'
    dest: '/etc/systemd/system/{{ item }}'
  loop:
    - turn-off-bluetooth@.service
    - mpc-reload.service
    - mpc-reload.timer
    - newsboat-reload.service
    - newsboat-reload.timer
    - pacman-update-files-database.service
    - pacman-update-files-database.timer
    - fetch-dotfiles.service
    - fetch-dotfiles.timer
    - docker-limit.slice

- name: reload units
  systemd:
    daemon_reload: yes
  when: not in_docker

- name: enable and start services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  loop:
    - bluetooth.service
    - docker.service
    - mpc-reload.timer
    - newsboat-reload.timer
    - pacman-update-files-database.timer
    - paccache.timer  # Discard unused packages weekly.
    - systemd-timesyncd.service  # Sync time.
    - fetch-dotfiles.timer
    - tlp.service
  when: not in_docker

- name: start docker resource limit slice
  systemd:
    name: docker-limit.slice
    state: started
  when: not in_docker

- name: enable turn-off-bluetooth service
  systemd:
    name: 'turn-off-bluetooth@{{ user_name }}'
    enabled: yes
  when: not in_docker

- name: install user unit files
  become: yes
  become_user: '{{ user_name }}'
  copy:
    src: '{{ item }}'
    dest: '{{ user_home }}/.config/systemd/user/{{ item }}'
  loop:
    - battery-notification.service

- name: reload user units
  become: yes
  become_user: '{{ user_name }}'
  systemd:
    daemon_reload: yes
    scope: user
  when: not in_docker

- name: enable and start user services
  become: yes
  become_user: '{{ user_name }}'
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
    scope: user
  loop:
    - mpd.service
    - syncthing.service
    - battery-notification.service
  when: not in_docker
