---
- name: configure keyboard and touchpad for X11
  copy:
    src: '{{ item }}'
    dest: /etc/X11/xorg.conf.d/
  loop:
    - 00-keyboard.conf
    - 10-touchpad.conf

- name: configure keyboard and font for virtual console
  command:
    cmd: '{{ role_path }}/files/vconsole.sh'

- name: create directories in user_home
  file:
    path: '{{ item.value }}'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_group }}'
  loop: '{{ dirs | dict2items }}'

- name: create symlinks
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - {
      src: '{{ dirs.dotfiles_local }}',
      dest: '{{ dotfiles_home }}/.dotfiles.local'
    }
    - {
      src: '{{ dotfiles_home }}/ansible/ansible.cfg',
      dest: '{{ user_home }}/.ansible.cfg'
    }
    - {
      src: '{{ dotfiles_home }}/ansible/bootstrap',
      dest: '{{ dirs.dot_local_bin }}/bootstrap'
    }

# https://wiki.archlinux.org/index.php/GNOME/Keyring#PAM_method
- name: configure PAM for GNOME Keyring
  lineinfile:
    path: /etc/pam.d/login
    line: '{{ item.line }}'
    regexp: '{{ item.line }}'
    insertafter: '{{ item.pattern }}'
  loop:
    - {
      line: 'auth       optional     pam_gnome_keyring.so',
      pattern: '^auth'
    }
    - {
      line: 'session    optional     pam_gnome_keyring.so auto_start',
      pattern: '^session'
    }

- name: configure default directory for Syncthing
  lineinfile:
    path: '{{ user_home }}/.config/syncthing/config.xml'
    # Keep the indentation level.
    line: '        <defaultFolderPath>~/sync</defaultFolderPath>'
    regexp: '<defaultFolderPath>.*</defaultFolderPath>'
  ignore_errors: yes

- name: configure pacman
  lineinfile:
    path: '/etc/pacman.conf'
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
  loop:
    - {
      line: 'VerbosePkgLists',
      regexp: '^#[ ]?VerbosePkgLists$'
    }
    - {
      line: 'IgnoreGroup = custom',
      regexp: '^#[ ]?IgnoreGroup ='
    }

- name: get submodules
  become: yes
  become_user: '{{ user_name }}'
  command:
    cmd: git submodule update --init --recursive
    chdir: '{{ dotfiles_home }}'

- name: generate helptags for vim
  become: yes
  become_user: '{{ user_name }}'
  command:
    cmd: vim -c 'helptags ALL' -c 'quit'

- name: add user to groups
  user:
    name: '{{ user_name }}'
    groups: '{{ item }}'
    append: yes
  loop:
    - docker
    - video

- name: install gtk keymaps
  copy:
    src: gtk-keys.css
    dest: /usr/share/themes/Custom/gtk-3.0/

- name: set zsh as default shell for non-root user
  user:
    name: '{{ user_name }}'
    shell: /bin/zsh
