---
- name: create directories in user_home
  file:
    path: "{{ user_home }}/{{ item.path }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
  loop:
    - { path: .local/bin }
    - { path: .vim }
    - { path: .vim/ultisnips }
    - { path: documents }
    - { path: downloads }
    - { path: downloads/firefox }
    - { path: pictures }
    - { path: pictures/screenshots }
    - { path: sync }

- name: create .dotfiles.local symlink
  file:
    src: '{{ user_home }}/.dotfiles.local'
    dest: '{{ dotfiles_home }}/.dotfiles.local'
    state: link

# https://wiki.archlinux.org/index.php/GNOME/Keyring#PAM_method
- name: configure PAM for GNOME Keyring
  lineinfile:
    path: /etc/pam.d/login
    line: '{{ item.line }}'
    regexp: '{{ item.line }}'
    insertafter: '{{ item.pattern }}'
  loop:
    - {
      line: 'auth       optional     pam_gnome_keyring.so',
      pattern: '^auth'
    }
    - {
      line: 'session    optional     pam_gnome_keyring.so auto_start',
      pattern: '^session'
    }
