---
- name: put NetworkManager dns config in place
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - {
      src: dns.conf,
      dest: /etc/NetworkManager/conf.d/
    }
    - {
      src: mac.conf,
      dest: /etc/NetworkManager/conf.d/
    }
    - {
      src: dnsmasq/00-general.conf,
      dest: /etc/NetworkManager/dnsmasq.d/
    }
