---
- name: set up an Arch Linux machine
  hosts: localhost
  become: yes
  roles:
    - main
    - pacman
    - systemd
    - python
  vars:
    - user_home: "{{ '~' | expanduser }}"
    - dotfiles_home: "{{ user_home }}/.dotfiles"
    - user_name: user
    - user_group: user
