---
- name: set up an Arch Linux machine
  hosts: localhost
  become: yes
  roles:
    - pacman
    - systemd
  vars:
    - user_home: "{{ '~' | expanduser }}"
    - dotfiles_home: "{{ user_home }}/.dotfiles"
