#!/bin/sh
# Run ansible-playbook, accept role tags as args.
# Example:
# bootstrap firefox systemd

! [ -x "$(which ansible)" ] && sudo pacman --noconfirm -S ansible

export ANSIBLE_PYTHON_INTERPRETER=auto_silent

[ -n "$1" ] &&
    tags_arg="$(printf " --tags %s" "$@")"

# Don't double quote for word-splitting of args.
ansible-playbook -i ~/.dotfiles/ansible/hosts --ask-become-pass ~/.dotfiles/ansible/playbook.yml $tags_arg
