---
- name: set up an Arch Linux machine
  hosts: localhost
  become: yes
  roles:
    - misc
    - pacman
    - systemd
    - python
    - npm
    - stow
    - pkgbuilds
    - aur
    - firefox
    - transmission
    - virtualbox
  vars:
    - user_home: "{{ '~' | expanduser }}"
    - dotfiles_home: "{{ user_home }}/.dotfiles"
    - user_name: user
    - user_group: user

- name: import local playbook
  import_playbook: "{{ user_home }}/.dotfiles.local/ansible/playbook.yml"
  vars:
    user_home: "{{ '~' | expanduser }}"
