---
- name: set up an Arch Linux machine
  hosts: localhost
  become: yes
  roles:
    # Install various packages.
    - { role: pacman, tags: pacman }
    - { role: python, tags: python }
    - { role: npm, tags: npm }
    - { role: ruby, tags: ruby }
    - { role: aur, tags: aur }
    - { role: pkgbuilds, tags: pkgbuilds }
    # Other roles.
    - { role: misc, tags: misc }
    - { role: stow, tags: stow }
    - { role: firefox, tags: firefox }
    - { role: transmission, tags: transmission }
    - { role: virtualbox, tags: virtualbox }
    - { role: systemd, tags: systemd }
