---
- name: set up an Arch Linux machine
  hosts: localhost
  become: yes
  roles:
    - { role: misc, tags: misc }
    - { role: pacman, tags: pacman }
    - { role: systemd, tags: systemd }
    - { role: python, tags: python }
    - { role: npm, tags: npm }
    - { role: stow, tags: stow }
    - { role: pkgbuilds, tags: pkgbuilds }
    - { role: aur, tags: aur }
    - { role: firefox, tags: firefox }
    - { role: transmission, tags: transmission }
    - { role: virtualbox, tags: virtualbox }

- name: import local playbook
  import_playbook: "{{ user_home }}/.dotfiles.local/ansible/playbook.yml"
  tags: local
  vars:
    user_home: "{{ '~' | expanduser }}"
