---
- name: clone AUR pkgbuilds
  become: yes
  become_user: "{{ user_name }}"
  git:
    repo: 'https://aur.archlinux.org/{{ item }}.git'
    dest: '{{ aur_pkg_dir }}/{{ item }}'
    force: yes # Discard local modifications.
  loop: '{{ python_deps + packages }}'

- name: make and install AUR packages
  become: yes
  become_user: "{{ user_name }}"
  command:
    cmd: makepkg -si --cleanbuild --clean --noconfirm --needed --rmdeps
    chdir: '{{ aur_pkg_dir }}/{{ item }}'
  loop: '{{ python_deps + packages }}'
