#!/bin/sh
# Reload .Xresources.
alias xup='xrdb ~/.Xresources'
# Reload .bashrc.
alias bup='source ~/.bashrc'
# Reload .tmux.conf.
alias tup='tmux source-file ~/.tmux.conf'
# Reload Readline's .inputrc.
alias rup='bind -f ~/.inputrc'
# Restart i3.
alias iup='i3-msg restart'

alias ls='ls -p --color=auto'
# -h - with -l and -s, print sizes like 1K 234M 2G etc.
alias ll='ls -AlFh'

# -r - copy directories recursively
# -i - prompt before overwrite
alias cp='cp -ir'
# -i - prompt before overwrite
alias mv='mv -i'

# Highlight matches, ignore case distinctions.
alias grep='grep --color=auto --ignore-case'
# -n - output line numbers
# -I - ignore binary files
alias gr='grep -n -I'

# Find.
# -L - follow symbolic links
alias fn='find -L . -name'
# Case-insensitive.
alias fin='find -L . -iname'

# Could not make git alias script work the same way docker and lab
# aliases work, i.e. `alias git='git_alias'` inside the `git_aliases`
# script. There was what looked like an infinite loop when trying to
# reload .bashrc.
alias g='git_alias'
alias l='lab'

# Kill processes by name.
alias ka='killall'

alias d='docker'
alias c='docker-compose'

# Pacman.
alias p='pacman'

# Open ranger.
# The ranger-cd version switches the directory in bash on exit,
# ranger-shell.sh allows to expand shell aliases inside the :shell
# command.
alias r='SHELL=~/.local/bin/ranger-shell.sh ranger-cd'

alias t='tmux'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'

# Open (with) vim.
alias v='vim'
alias vm='vman '
alias vs='vim -S'

# The space at the end allows the next command word following the alias
# to also be checked for alias expansion.
alias s='sudo '

# Create directory.
# -p - no error if existing, make parent directories as needed.
# -v - print a message for each created directory.
alias mkd='mkdir -pv'

alias tch='touch'

alias nb='newsboat'

alias py='python'
alias ipy='ipython'
# Python virtualenvwrapper.
alias wo='workon'
alias deac='deactivate'

alias bandcamp-dl='bandcamp-dl --base-dir="$(xdg-user-dir DOWNLOAD)"/bandcamp-dl'

alias yd='youtube-dl'
# Download playlists using a separate config.
# The config specifies different directory structure.
alias ydp='youtube-dl --config-location ~/.config/youtube-dl-playlist.conf'
# There are options to download subtitles in the main config file,
# the subtitles are not needed for audio-only downloads, and can't
# be merged into an audio file, so a separate config file for audio
# is needed, without the subtitle options.
alias yda='youtube-dl --config-location ~/.config/youtube-dl-audio.conf'

# --auto-vertical-output - automatically switch to vertical output
# mode if the result is wider than the terminal width.
alias mycli='mycli --auto-vertical-output'

alias dpl='dotfiles_pull'
alias dps='dotfiles_push'

alias sctl='systemctl'
alias jctl='journalctl'

# Tor start/stop.
alias toron='sudo systemctl start tor.service'
alias toroff='sudo systemctl stop tor.service'

# Empty trash.
alias et='gio trash --empty'

alias nb='newsboat'

alias get-ranger-maps='get-ranger-maps ~/.config/ranger/bookmark_maps.conf ~/.config/shortcuts ~/.config/shortcuts.local'
