#!/usr/bin/env bash
u() {
    # Go up $1 directories.
    # If $1 is omitted or is not an integer, go up 1 directory.
    dir=''
    if echo "$1" | grep -Eq '^[0-9]+$'; then
        for i in $(seq "$1")
        do
            dir="$dir../"
        done
    else
        dir='..'
    fi
    cd "$dir"
}

ww() {
    # Open index file of the $1 wiki (the first one if $1 is omitted).
    vim -c "execute \"normal $1\<Plug>VimwikiIndex\""
}

fzg() {
    # Open a directory from special files containing a list of shortcuts.
    cd "$(fzf_shortcuts ~/.config/shortcuts ~/.config/shortcuts.local)" ||
        return 1
}

vim_session_venv() {
    # Get a directory to venv mapping from a file, activate venv
    # before launching vim with the session of the directory.
    # Do not change venv if already in a venv.
    #
    # File example:
    # /home/user/directory1 venv1
    # /home/user/directory2 venv2
    #
    # Usage example:
    # vim_session_venv ~/.config/venv_mapping
    if [ -z "$VIRTUAL_ENV" ]; then
        venv_mapping_file="$1"
        if [ -n "$venv_mapping_file" ] && [ -f "$venv_mapping_file" ]; then
            venv_name="$(grep "$(pwd)" "$venv_mapping_file" | awk '{ print $2 }')"
            [ -n "$venv_name" ] && workon "$venv_name"
        fi
    fi

    vim -c 'WrappedObsession'
}

ranger-cd() {
    # Automatically change the directory in bash after closing ranger.
    # Source:
    # https://github.com/ranger/ranger/blob/master/examples/bash_automatic_cd.sh
    # The same script can be found locally:
    # /usr/share/doc/ranger/examples/bash_automatic_cd.sh
    #
    # This is a function for automatically changing the directory to
    # the last visited one after ranger quits.
    # To undo the effect of this function, you can type "cd -" to return to the
    # original directory.
    tempfile="$(mktemp -t tmp.XXXXXX)"
    ranger --choosedir="$tempfile" "${@:-$(pwd)}"
    test -f "$tempfile" &&
    if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
        cd -- "$(cat "$tempfile")"
    fi
    rm -f -- "$tempfile"
}

wrap_ranger() {
    # Temporary workaround for tmux renaming problem.
    [ -z "$TMUX" ] || current_window_name="$(tmux display-message -p '#W')"
    # The ranger-cd version switches the directory in bash on exit,
    # ranger-shell.sh allows to expand shell aliases inside the :shell
    # command.
    SHELL=~/.local/bin/ranger-shell.sh ranger-cd
    [ -z "$current_window_name" ] || tmux rename-window "$current_window_name"
}

rmnt() {
    # Go to a mounted partition's directory.
    choice="$(fzf_mounted)"
    [ -n "$choice" ] && ranger-cd "$choice"
}

cmnt() {
    choice="$(fzf_mounted)"
    [ -n "$choice" ] && cd "$choice"
}
