#!/bin/sh
# Aliases for systemctl.
systemctl_alias() {
    key="$1"
    case "$key" in
        lt)
            cmd="list-timers";;
        lu)
            cmd="list-units";;
        rs)
            cmd="restart";;
        sp)
            cmd="stop";;
        sr)
            cmd="start";;
        st)
            cmd="status";;
        *)
            cmd="$key";;
    esac
    shift
    systemctl $cmd "$@"
}

alias systemctl='systemctl_alias'
