name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9
      - name: Install linters
        run: pip install pre-commit==3.0.4 flake8==6.0.0
      - run: pre-commit install
      - run: pre-commit run --all-files
      - name: Run shellcheck on all the scripts with sh shebang
        run: |
          find ./scripts/ -type f -print0 |
              xargs -0 gawk '/^#!.*( |[/])sh/{printf "%s\0", FILENAME} {nextfile}' |
              xargs -0 shellcheck
      - name: Run flake8 on the scripts directory
        run: flake8 ./scripts/
      - name: Run flake8 on all the scripts with python shebang  # By default, only *.py files are processed.
        run: |
          find ./scripts/ -type f -print0 |
              xargs -0 gawk '/^#!.*( |[/])python3?$/{printf "%s\0", FILENAME} {nextfile}' |
              xargs -0 flake8

  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t "$DOCKER_USERNAME"/dotfiles .
      - name: Push image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [ "$GITHUB_REF" == "refs/heads/arch" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
              docker push "$DOCKER_USERNAME"/dotfiles;
          fi
